/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PiratasGUI;

import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author Personal
 */
public class PiratasGUI extends javax.swing.JFrame {
    /**
     * Creates new form PiratasGUI
     */
//    private Barco labelBarco;
    private Barco BarcoMovement;
//    private JLabel labelBarco;
    public PiratasGUI() {
        initComponents();
        /*Ventana*/
   
        this.setContentPane(new FondoPanel("/images/playa.png"));
        this.setBounds(0, 0, 1366, 768);
        
//        labelBarco = new JLabel();
//        labelBarco.setIcon(new ImageIcon("C:\\Users\\Toshiba PC\\Documents\\NetBeansProjects\\PiratasUCAB\\src\\images\\barcoPirata.png"));
//        add(labelBarco);
//        labelBarco.setLocation(10,10);
//        labelBarco.setVisible(true);
        
        BarcoMovement = new Barco(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        barcoPiratainf = new FondoPanel("/images/pirata.png");
        javax.swing.JPanel barcoReinainf2 = new FondoPanel("/images/interceptor.png");
        barcoReinainf = new FondoPanel("/images/invencible.png");
        jMenuBar1 = new javax.swing.JMenuBar();
        iniciar = new javax.swing.JMenu();
        cargar = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1300, 768));
        setMinimumSize(new java.awt.Dimension(1300, 768));
        setPreferredSize(new java.awt.Dimension(708, 768));
        getContentPane().setLayout(null);

        javax.swing.GroupLayout barcoPiratainfLayout = new javax.swing.GroupLayout(barcoPiratainf);
        barcoPiratainf.setLayout(barcoPiratainfLayout);
        barcoPiratainfLayout.setHorizontalGroup(
            barcoPiratainfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 158, Short.MAX_VALUE)
        );
        barcoPiratainfLayout.setVerticalGroup(
            barcoPiratainfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 240, Short.MAX_VALUE)
        );

        getContentPane().add(barcoPiratainf);
        barcoPiratainf.setBounds(10, 7, 158, 240);

        javax.swing.GroupLayout barcoReinainf2Layout = new javax.swing.GroupLayout(barcoReinainf2);
        barcoReinainf2.setLayout(barcoReinainf2Layout);
        barcoReinainf2Layout.setHorizontalGroup(
            barcoReinainf2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 158, Short.MAX_VALUE)
        );
        barcoReinainf2Layout.setVerticalGroup(
            barcoReinainf2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 240, Short.MAX_VALUE)
        );

        getContentPane().add(barcoReinainf2);
        barcoReinainf2.setBounds(10, 498, 158, 240);

        javax.swing.GroupLayout barcoReinainfLayout = new javax.swing.GroupLayout(barcoReinainf);
        barcoReinainf.setLayout(barcoReinainfLayout);
        barcoReinainfLayout.setHorizontalGroup(
            barcoReinainfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 158, Short.MAX_VALUE)
        );
        barcoReinainfLayout.setVerticalGroup(
            barcoReinainfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 240, Short.MAX_VALUE)
        );

        getContentPane().add(barcoReinainf);
        barcoReinainf.setBounds(10, 253, 158, 240);

        iniciar.setText("Iniciar");
        iniciar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                iniciarMouseClicked(evt);
            }
        });
        jMenuBar1.add(iniciar);
        iniciar.getAccessibleContext().setAccessibleDescription("");

        cargar.setText("Cargar XML");
        jMenuBar1.add(cargar);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void iniciarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iniciarMouseClicked
        // TODO add your handling code here:
        this.BarcoMovement.movimiento.start();
        this.BarcoMovement.iniciar(1);

    }//GEN-LAST:event_iniciarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PiratasGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PiratasGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PiratasGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PiratasGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PiratasGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel barcoPiratainf;
    private javax.swing.JPanel barcoReinainf;
    private javax.swing.JMenu cargar;
    private javax.swing.JMenu iniciar;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
